# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gombe/pico-examples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gombe/pico-examples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/gombe/pico-examples && $(CMAKE_COMMAND) -E cmake_progress_start /home/gombe/pico-examples/CMakeFiles /home/gombe/pico-examples/spi/spi_dma/CMakeFiles/progress.marks
	cd /home/gombe/pico-examples && $(MAKE) -f CMakeFiles/Makefile2 spi/spi_dma/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gombe/pico-examples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/gombe/pico-examples && $(MAKE) -f CMakeFiles/Makefile2 spi/spi_dma/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/gombe/pico-examples && $(MAKE) -f CMakeFiles/Makefile2 spi/spi_dma/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/gombe/pico-examples && $(MAKE) -f CMakeFiles/Makefile2 spi/spi_dma/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/gombe/pico-examples && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
spi/spi_dma/CMakeFiles/spi_dma.dir/rule:
	cd /home/gombe/pico-examples && $(MAKE) -f CMakeFiles/Makefile2 spi/spi_dma/CMakeFiles/spi_dma.dir/rule
.PHONY : spi/spi_dma/CMakeFiles/spi_dma.dir/rule

# Convenience name for target.
spi_dma: spi/spi_dma/CMakeFiles/spi_dma.dir/rule

.PHONY : spi_dma

# fast build rule for target.
spi_dma/fast:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/build
.PHONY : spi_dma/fast

3dmain.obj: 3dmain.cpp.obj

.PHONY : 3dmain.obj

# target to build an object file
3dmain.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/3dmain.cpp.obj
.PHONY : 3dmain.cpp.obj

3dmain.i: 3dmain.cpp.i

.PHONY : 3dmain.i

# target to preprocess a source file
3dmain.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/3dmain.cpp.i
.PHONY : 3dmain.cpp.i

3dmain.s: 3dmain.cpp.s

.PHONY : 3dmain.s

# target to generate assembly for a file
3dmain.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/3dmain.cpp.s
.PHONY : 3dmain.cpp.s

font.obj: font.c.obj

.PHONY : font.obj

# target to build an object file
font.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/font.c.obj
.PHONY : font.c.obj

font.i: font.c.i

.PHONY : font.i

# target to preprocess a source file
font.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/font.c.i
.PHONY : font.c.i

font.s: font.c.s

.PHONY : font.s

# target to generate assembly for a file
font.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/font.c.s
.PHONY : font.c.s

fvector2.obj: fvector2.cpp.obj

.PHONY : fvector2.obj

# target to build an object file
fvector2.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/fvector2.cpp.obj
.PHONY : fvector2.cpp.obj

fvector2.i: fvector2.cpp.i

.PHONY : fvector2.i

# target to preprocess a source file
fvector2.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/fvector2.cpp.i
.PHONY : fvector2.cpp.i

fvector2.s: fvector2.cpp.s

.PHONY : fvector2.s

# target to generate assembly for a file
fvector2.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/fvector2.cpp.s
.PHONY : fvector2.cpp.s

fvector3.obj: fvector3.cpp.obj

.PHONY : fvector3.obj

# target to build an object file
fvector3.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/fvector3.cpp.obj
.PHONY : fvector3.cpp.obj

fvector3.i: fvector3.cpp.i

.PHONY : fvector3.i

# target to preprocess a source file
fvector3.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/fvector3.cpp.i
.PHONY : fvector3.cpp.i

fvector3.s: fvector3.cpp.s

.PHONY : fvector3.s

# target to generate assembly for a file
fvector3.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/fvector3.cpp.s
.PHONY : fvector3.cpp.s

home/gombe/pico-sdk/src/common/pico_sync/critical_section.obj: home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/critical_section.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.obj

home/gombe/pico-sdk/src/common/pico_sync/critical_section.i: home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/critical_section.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.i

home/gombe/pico-sdk/src/common/pico_sync/critical_section.s: home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/critical_section.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/critical_section.c.s

home/gombe/pico-sdk/src/common/pico_sync/lock_core.obj: home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/lock_core.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.obj

home/gombe/pico-sdk/src/common/pico_sync/lock_core.i: home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/lock_core.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.i

home/gombe/pico-sdk/src/common/pico_sync/lock_core.s: home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/lock_core.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/lock_core.c.s

home/gombe/pico-sdk/src/common/pico_sync/mutex.obj: home/gombe/pico-sdk/src/common/pico_sync/mutex.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/mutex.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_sync/mutex.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/mutex.c.obj

home/gombe/pico-sdk/src/common/pico_sync/mutex.i: home/gombe/pico-sdk/src/common/pico_sync/mutex.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/mutex.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_sync/mutex.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/mutex.c.i

home/gombe/pico-sdk/src/common/pico_sync/mutex.s: home/gombe/pico-sdk/src/common/pico_sync/mutex.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/mutex.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_sync/mutex.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/mutex.c.s

home/gombe/pico-sdk/src/common/pico_sync/sem.obj: home/gombe/pico-sdk/src/common/pico_sync/sem.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/sem.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_sync/sem.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/sem.c.obj

home/gombe/pico-sdk/src/common/pico_sync/sem.i: home/gombe/pico-sdk/src/common/pico_sync/sem.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/sem.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_sync/sem.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/sem.c.i

home/gombe/pico-sdk/src/common/pico_sync/sem.s: home/gombe/pico-sdk/src/common/pico_sync/sem.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_sync/sem.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_sync/sem.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_sync/sem.c.s

home/gombe/pico-sdk/src/common/pico_time/time.obj: home/gombe/pico-sdk/src/common/pico_time/time.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_time/time.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_time/time.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_time/time.c.obj

home/gombe/pico-sdk/src/common/pico_time/time.i: home/gombe/pico-sdk/src/common/pico_time/time.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_time/time.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_time/time.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_time/time.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_time/time.c.i

home/gombe/pico-sdk/src/common/pico_time/time.s: home/gombe/pico-sdk/src/common/pico_time/time.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_time/time.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_time/time.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_time/time.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_time/time.c.s

home/gombe/pico-sdk/src/common/pico_time/timeout_helper.obj: home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_time/timeout_helper.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.obj

home/gombe/pico-sdk/src/common/pico_time/timeout_helper.i: home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_time/timeout_helper.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.i

home/gombe/pico-sdk/src/common/pico_time/timeout_helper.s: home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_time/timeout_helper.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_time/timeout_helper.c.s

home/gombe/pico-sdk/src/common/pico_util/datetime.obj: home/gombe/pico-sdk/src/common/pico_util/datetime.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_util/datetime.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_util/datetime.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_util/datetime.c.obj

home/gombe/pico-sdk/src/common/pico_util/datetime.i: home/gombe/pico-sdk/src/common/pico_util/datetime.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_util/datetime.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_util/datetime.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_util/datetime.c.i

home/gombe/pico-sdk/src/common/pico_util/datetime.s: home/gombe/pico-sdk/src/common/pico_util/datetime.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_util/datetime.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_util/datetime.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_util/datetime.c.s

home/gombe/pico-sdk/src/common/pico_util/pheap.obj: home/gombe/pico-sdk/src/common/pico_util/pheap.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_util/pheap.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_util/pheap.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_util/pheap.c.obj

home/gombe/pico-sdk/src/common/pico_util/pheap.i: home/gombe/pico-sdk/src/common/pico_util/pheap.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_util/pheap.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_util/pheap.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_util/pheap.c.i

home/gombe/pico-sdk/src/common/pico_util/pheap.s: home/gombe/pico-sdk/src/common/pico_util/pheap.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_util/pheap.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_util/pheap.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_util/pheap.c.s

home/gombe/pico-sdk/src/common/pico_util/queue.obj: home/gombe/pico-sdk/src/common/pico_util/queue.c.obj

.PHONY : home/gombe/pico-sdk/src/common/pico_util/queue.obj

# target to build an object file
home/gombe/pico-sdk/src/common/pico_util/queue.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : home/gombe/pico-sdk/src/common/pico_util/queue.c.obj

home/gombe/pico-sdk/src/common/pico_util/queue.i: home/gombe/pico-sdk/src/common/pico_util/queue.c.i

.PHONY : home/gombe/pico-sdk/src/common/pico_util/queue.i

# target to preprocess a source file
home/gombe/pico-sdk/src/common/pico_util/queue.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : home/gombe/pico-sdk/src/common/pico_util/queue.c.i

home/gombe/pico-sdk/src/common/pico_util/queue.s: home/gombe/pico-sdk/src/common/pico_util/queue.c.s

.PHONY : home/gombe/pico-sdk/src/common/pico_util/queue.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/common/pico_util/queue.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : home/gombe/pico-sdk/src/common/pico_util/queue.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.obj: home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.i: home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.s: home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj: home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.i: home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.s: home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_divider/divider.obj: home/gombe/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_divider/divider.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj

home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.obj: home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.i: home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.s: home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj: home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.i: home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.s: home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.obj: home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.i: home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.s: home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj: home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj

home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.obj: home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.i: home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.s: home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.obj: home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.i: home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.s: home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.obj: home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.i: home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.s: home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.obj: home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.i: home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.s: home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.obj: home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.i: home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.s: home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj: home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.i: home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.s: home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj: home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i: home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s: home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s

home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj: home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj

home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.i: home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i

home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.s: home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s

home/gombe/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj: home/gombe/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj: home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i: home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i

home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s: home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s

home/gombe/pico-sdk/src/rp2_common/pico_divider/divider.obj: home/gombe/pico-sdk/src/rp2_common/pico_divider/divider.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_divider/divider.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_divider/divider.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_divider/divider.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj: home/gombe/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj: home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.i: home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i

home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.s: home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s

home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.obj: home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.i: home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.i

home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.s: home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.c.s

home/gombe/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj: home/gombe/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj: home/gombe/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj: home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.i: home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i

home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.s: home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s

home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.obj: home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.i: home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.i

home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.s: home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.c.s

home/gombe/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj: home/gombe/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj: home/gombe/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj: home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i: home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i

home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s: home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s

home/gombe/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj: home/gombe/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.obj: home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.i: home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i

home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.s: home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s

home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.obj: home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.i: home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.i

home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.s: home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.c.s

home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.obj: home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.i: home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.i

home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.s: home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.c.s

home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.obj: home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.i: home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i

home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.s: home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s

home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj: home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i: home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i

home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s: home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s

home/gombe/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj: home/gombe/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj

home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj: home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj

home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i: home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i

home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s: home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s

home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.obj: home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.i: home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i

home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.s: home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s

home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj: home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i: home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i

home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s: home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s

home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj: home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj

# target to build an object file
home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i: home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i

# target to preprocess a source file
home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i

home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s: home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s

.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s

# target to generate assembly for a file
home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s

ili9341.obj: ili9341.cpp.obj

.PHONY : ili9341.obj

# target to build an object file
ili9341.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/ili9341.cpp.obj
.PHONY : ili9341.cpp.obj

ili9341.i: ili9341.cpp.i

.PHONY : ili9341.i

# target to preprocess a source file
ili9341.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/ili9341.cpp.i
.PHONY : ili9341.cpp.i

ili9341.s: ili9341.cpp.s

.PHONY : ili9341.s

# target to generate assembly for a file
ili9341.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/ili9341.cpp.s
.PHONY : ili9341.cpp.s

kbhit.obj: kbhit.c.obj

.PHONY : kbhit.obj

# target to build an object file
kbhit.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/kbhit.c.obj
.PHONY : kbhit.c.obj

kbhit.i: kbhit.c.i

.PHONY : kbhit.i

# target to preprocess a source file
kbhit.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/kbhit.c.i
.PHONY : kbhit.c.i

kbhit.s: kbhit.c.s

.PHONY : kbhit.s

# target to generate assembly for a file
kbhit.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/kbhit.c.s
.PHONY : kbhit.c.s

main.obj: main.c.obj

.PHONY : main.obj

# target to build an object file
main.c.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/main.c.s
.PHONY : main.c.s

matrix4.obj: matrix4.cpp.obj

.PHONY : matrix4.obj

# target to build an object file
matrix4.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/matrix4.cpp.obj
.PHONY : matrix4.cpp.obj

matrix4.i: matrix4.cpp.i

.PHONY : matrix4.i

# target to preprocess a source file
matrix4.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/matrix4.cpp.i
.PHONY : matrix4.cpp.i

matrix4.s: matrix4.cpp.s

.PHONY : matrix4.s

# target to generate assembly for a file
matrix4.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/matrix4.cpp.s
.PHONY : matrix4.cpp.s

spi_dma.obj: spi_dma.cpp.obj

.PHONY : spi_dma.obj

# target to build an object file
spi_dma.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/spi_dma.cpp.obj
.PHONY : spi_dma.cpp.obj

spi_dma.i: spi_dma.cpp.i

.PHONY : spi_dma.i

# target to preprocess a source file
spi_dma.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/spi_dma.cpp.i
.PHONY : spi_dma.cpp.i

spi_dma.s: spi_dma.cpp.s

.PHONY : spi_dma.s

# target to generate assembly for a file
spi_dma.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/spi_dma.cpp.s
.PHONY : spi_dma.cpp.s

texturepoly.obj: texturepoly.cpp.obj

.PHONY : texturepoly.obj

# target to build an object file
texturepoly.cpp.obj:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/texturepoly.cpp.obj
.PHONY : texturepoly.cpp.obj

texturepoly.i: texturepoly.cpp.i

.PHONY : texturepoly.i

# target to preprocess a source file
texturepoly.cpp.i:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/texturepoly.cpp.i
.PHONY : texturepoly.cpp.i

texturepoly.s: texturepoly.cpp.s

.PHONY : texturepoly.s

# target to generate assembly for a file
texturepoly.cpp.s:
	cd /home/gombe/pico-examples && $(MAKE) -f spi/spi_dma/CMakeFiles/spi_dma.dir/build.make spi/spi_dma/CMakeFiles/spi_dma.dir/texturepoly.cpp.s
.PHONY : texturepoly.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... spi_dma"
	@echo "... 3dmain.obj"
	@echo "... 3dmain.i"
	@echo "... 3dmain.s"
	@echo "... font.obj"
	@echo "... font.i"
	@echo "... font.s"
	@echo "... fvector2.obj"
	@echo "... fvector2.i"
	@echo "... fvector2.s"
	@echo "... fvector3.obj"
	@echo "... fvector3.i"
	@echo "... fvector3.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/critical_section.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/critical_section.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/critical_section.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/lock_core.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/lock_core.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/lock_core.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/mutex.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/mutex.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/mutex.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/sem.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/sem.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_sync/sem.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_time/time.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_time/time.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_time/time.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_time/timeout_helper.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_time/timeout_helper.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_time/timeout_helper.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/datetime.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/datetime.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/datetime.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/pheap.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/pheap.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/pheap.s"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/queue.obj"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/queue.i"
	@echo "... home/gombe/pico-sdk/src/common/pico_util/queue.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_claim/claim.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_clocks/clocks.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_divider/divider.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_dma/dma.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_gpio/gpio.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_pll/pll.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_spi/spi.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_sync/sync.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_timer/timer.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_uart/uart.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_vreg/vreg.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/hardware_xosc/xosc.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_divider/divider.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_init_rom.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_math.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_init_rom.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_math.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_multicore/multicore.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_platform/platform.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_printf/printf.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_runtime/runtime.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdio/stdio.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i"
	@echo "... home/gombe/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s"
	@echo "... ili9341.obj"
	@echo "... ili9341.i"
	@echo "... ili9341.s"
	@echo "... kbhit.obj"
	@echo "... kbhit.i"
	@echo "... kbhit.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... matrix4.obj"
	@echo "... matrix4.i"
	@echo "... matrix4.s"
	@echo "... spi_dma.obj"
	@echo "... spi_dma.i"
	@echo "... spi_dma.s"
	@echo "... texturepoly.obj"
	@echo "... texturepoly.i"
	@echo "... texturepoly.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/gombe/pico-examples && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

